package com.example.bookshelf.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF845415)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDDBB)
val onPrimaryContainerLight = Color(0xFF2B1700)
val secondaryLight = Color(0xFF725A41)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFDDDBD)
val onSecondaryContainerLight = Color(0xFF281805)
val tertiaryLight = Color(0xFF56633C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD9E9B6)
val onTertiaryContainerLight = Color(0xFF141F01)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF211A14)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF211A14)
val surfaceVariantLight = Color(0xFFF1DFD0)
val onSurfaceVariantLight = Color(0xFF50453A)
val outlineLight = Color(0xFF827568)
val outlineVariantLight = Color(0xFFD4C4B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF372F27)
val inverseOnSurfaceLight = Color(0xFFFDEEE3)
val inversePrimaryLight = Color(0xFFFABA73)
val surfaceDimLight = Color(0xFFE5D8CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E6)
val surfaceContainerLight = Color(0xFFFAEBE0)
val surfaceContainerHighLight = Color(0xFFF4E6DA)
val surfaceContainerHighestLight = Color(0xFFEEE0D5)


val primaryDarkHighContrast = Color(0xFFFFFAF8)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBE76)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF8)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE4C5A7)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF5FFDB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC2D1A0)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF18120C)
val onBackgroundDarkHighContrast = Color(0xFFEEE0D5)
val surfaceDarkHighContrast = Color(0xFF18120C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF50453A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF8)
val outlineDarkHighContrast = Color(0xFFD9C8B9)
val outlineVariantDarkHighContrast = Color(0xFFD9C8B9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFEEE0D5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3F2400)
val surfaceDimDarkHighContrast = Color(0xFF18120C)
val surfaceBrightDarkHighContrast = Color(0xFF403830)
val surfaceContainerLowestDarkHighContrast = Color(0xFF130D07)
val surfaceContainerLowDarkHighContrast = Color(0xFF211A14)
val surfaceContainerDarkHighContrast = Color(0xFF251E17)
val surfaceContainerHighDarkHighContrast = Color(0xFF302921)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3B332C)







